# Generated by Django 2.2.12 on 2020-07-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_auto_20200724_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="r3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_r3",
                to="home.R456",
            ),
        ),
    ]
