# Generated by Django 2.2.12 on 2020-08-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_r4'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEW1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.BigIntegerField()),
            ],
        ),
    ]
